# Generated by Django 5.0.6 on 2025-07-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_duplicati',
            field=models.BooleanField(default=False, verbose_name='Nainštalovať Duplicati'),
        ),
        migrations.AddField(
            model_name='client',
            name='has_nextcloud',
            field=models.BooleanField(default=False, verbose_name='Nainštalovať Nextcloud'),
        ),
        migrations.AddField(
            model_name='client',
            name='has_odoo',
            field=models.BooleanField(default=True, verbose_name='Nainštalovať Odoo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='Názov spoločnosti'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kontaktná osoba'),
        ),
        migrations.AlterField(
            model_name='client',
            name='domain',
            field=models.CharField(max_length=255, verbose_name='Vlastná doména klienta'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Kontaktný email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='internal_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Interný názov (pre zložku)'),
        ),
    ]
