# Generated by Django 5.0.6 on 2025-07-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_has_duplicati_client_has_nextcloud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='Název společnosti'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kontaktní osoba'),
        ),
        migrations.AlterField(
            model_name='client',
            name='domain',
            field=models.CharField(max_length=255, verbose_name='Vlastní doména klienta'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Kontaktní email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='has_duplicati',
            field=models.BooleanField(default=False, verbose_name='Nainstalovat Duplicati'),
        ),
        migrations.AlterField(
            model_name='client',
            name='has_nextcloud',
            field=models.BooleanField(default=False, verbose_name='Nainstalovat Nextcloud'),
        ),
        migrations.AlterField(
            model_name='client',
            name='has_odoo',
            field=models.BooleanField(default=True, verbose_name='Nainstalovat Odoo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='internal_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Interní název (pro složku)'),
        ),
    ]
